//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Optique.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achat
    {
        public int num_achat { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<int> Prix { get; set; }
        public string Mode_Paiment { get; set; }
        public Nullable<System.DateTime> Date_Achat { get; set; }
        public Nullable<int> num_produit { get; set; }
        public Nullable<int> num_fournisseur { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
