//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Optique.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int num_facture { get; set; }
        public Nullable<System.DateTime> Date_facture { get; set; }
        public Nullable<int> num_vente { get; set; }
    
        public virtual Vente Vente { get; set; }
    }
}
