//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Optique.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesure
    {
        public int num_mesure { get; set; }
        public Nullable<System.DateTime> Date_Mesure { get; set; }
        public string mutualise { get; set; }
        public string Sphere_Mesure { get; set; }
        public string Cylindre_Mesure { get; set; }
        public Nullable<int> Axe { get; set; }
        public string Type_Lentille { get; set; }
        public string Lentille_Mesure { get; set; }
        public Nullable<double> Hauteur { get; set; }
        public string Oeil_Mesure { get; set; }
        public Nullable<int> num_ophtal { get; set; }
        public Nullable<int> num_client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Ophtalmologue Ophtalmologue { get; set; }
    }
}
